# Generated by Django 3.0.6 on 2020-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=255)),
                ('user_nm', models.CharField(default='', max_length=20)),
                ('user_mobile_no', models.CharField(default='', max_length=20)),
                ('user_ty', models.CharField(default='0', max_length=2)),
                ('device_token', models.CharField(default='', max_length=255)),
                ('cre_dt', models.DateTimeField(auto_now_add=True)),
                ('cre_id', models.CharField(max_length=20, null=True)),
                ('upt_dt', models.DateTimeField(auto_now=True)),
                ('upt_id', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'tb_user_info',
                'ordering': ('user_nm',),
                'managed': False,
            },
        ),
    ]
